# Generated by Django 5.1.1 on 2024-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank="True",
                max_length=400,
                null="True",
                verbose_name="Ссылка на оплату",
            ),
            preserve_default="True",
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank="True",
                max_length=255,
                null="True",
                verbose_name="ID сессии оплаты",
            ),
            preserve_default="True",
        ),
    ]
