services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"
    networks:
      - lms

  db:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
#    ports:
#      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lms

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO -P eventlet
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app
    networks:
      - lms

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l info -S django
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app
    networks:
      - lms

volumes:
  pg_data:

networks:
  lms:
    driver: bridge