# Generated by Django 5.1.1 on 2024-09-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса",
                        max_length=100,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True",
                        help_text="Опишите курс",
                        null="True",
                        verbose_name="Описание курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank="True",
                        help_text="Загрузите изображение для курса",
                        null="True",
                        upload_to="materials/course_image",
                        verbose_name="Изображение курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название урока",
                        max_length=100,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True",
                        help_text="Опишите урок",
                        null="True",
                        verbose_name="Описание урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank="True",
                        help_text="Загрузите изображение для урока",
                        null="True",
                        upload_to="materials/lesson_image",
                        verbose_name="Изображение урока",
                    ),
                ),
                (
                    "video",
                    models.TextField(
                        blank="True",
                        help_text="Вставьте ссылку на видео",
                        null="True",
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank="True",
                        help_text="Выберите курс",
                        null="True",
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
